version: '3.1'
services:
  database:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./setup/db/init.sql:/docker-entrypoint-initdb.d/0-init.sql